graphql/graphql-playground

packages/graphql-playground/src/components/Playground/TabBar.tsx

I found that this height causes scroll in Chrome running on Windows 10.

Fix TabBar scroll

---

packages/graphql-playground/src/middleware/express.ts

Added a type to the register argument, 'options', which fixes the following error when using the graphql-playground as an express middleware in TypeScript:
```
ERROR in /app/node_modules/graphql-playground/middleware/express.d.ts
(4,33): error TS7006: Parameter 'options' implicitly has an 'any' type.
```

Fix: express middleware TypeScript error

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
CODE_OF_CONDUCT.md

This commit add several items:
1. `CODE_OF_CONDUCT.md` - Code of conduct. Copied from [graphcool/graphcool](https://github.com/graphcool/graphcool/blob/master/CODE_OF_CONDUCT.md).
2. `CONTRIBUTING.md` - Contributing guidelines. Copied from [graphcool/chromeless](https://github.com/graphcool/chromeless/blob/master/CONTRIBUTING.md) repo and modified to update links.
3. `ISSUE_TEMPLATE.md` - Issue template applied when new issues are submitted. This helps structure issue reporting to a normalized level so maintainers can quickly understand the problem and respond.
**Other Notes**:
- The `CONTRIBUTING.md` and `ISSUE_TEMPLATE.md` files have been placed in a `.github` directory to keep from polluting the root. This is allowed by GitHub.
- There is the ability to add a `PULL_REQUEST_TEMPLATE.md` …

Adds contributing guidelines, issue template, and code of conduct.

---

packages/graphql-playground-electron/package.json
packages/graphql-playground-electron/src/ElectronApp.tsx
packages/graphql-playground-electron/src/main.ts

Adds the file association for GraphQL files to allow users to double-click to open a file.
Tested on macOS High Sierra
Closes #50

Add GraphQL file association

---

packages/graphql-playground/src/components/Playground.tsx

This tells fetch to include credentials when making the introspection query as well as other querires. Similar PR to https://github.com/graphcool/graphql-playground/pull/174
This is necessary for setups where every request gets routed through an auth path. 
/cc @wzrdzl @timsuchanek @kbrandwijk @schickling @morajabi

include credentials when fetching schema

---

packages/graphql-playground/src/components/Playground/QueryEditor.tsx
packages/graphql-playground/src/components/Playground/onHasCompletion.tsx

This should fix #307, it takes type from `codemirror-graphql/hint` and just prints it. Because hint already returns correct type. I can refactor it somewhere and remove commented out parts.

WIP: Auto-complete description

---

packages/graphql-playground-electron/src/ElectronApp.tsx

Not sure if I PR'ed this earlier. Apparently, I didn't.

fix: should suggest `graphql-cli` instead of `graphql`

---

README.md

Looks like the file structure was reorganized and these links didn't get updated.

Fix broken links to framework examples in README

---

packages/graphql-playground-react/src/components/MiddlewareApp.tsx
packages/graphql-playground-react/src/components/Playground.tsx

This PR fixes #364
The issue was due to [this](https://github.com/graphcool/graphql-playground/blame/0eb2492545d8c58de80eb8e435840e3fadc144b2/packages/graphql-playground-react/src/components/Playground.tsx#L1020). Tim must've commented that out because having `credentials: "include"` by default is not best practice, as it breaks requests to any server that does not have the correct `cors` options set up. Specifically, a server must know the domains of all the requesters in advance when `credentials: "include"`.
The change proposed here is very simple: 
- I have added `request.credentials: "omit"` to the default settings
- The new option only affects the `fetch()` call used to "post" GraphQL queries/mutations to the server
By having `"omit"` as a default setting, I preserve the current …

Make 'credentials' configurable for GQL requests

---

packages/graphql-playground-react/src/components/Playground/TopBar/TopBar.tsx

Fixes #499 .
- Reduced the size of the 'unreachable endpoint' loading spinner to match the mockup.
IMO, it looks very tiny now though, especially with the fade-out effect while it grows.

Fixed unreachable endpoint spinner size

---

packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx
packages/graphql-playground-react/src/components/Playground/TopBar/ReloadIcon.tsx
packages/graphql-playground-react/src/components/Playground/TopBar/TopBar.tsx

> Fixes #379.
--- 
- Simple animation on the reload icon when the schema is reloading (↔ `GraphQLEditor`'s `onReload` method is triggered)
- Two SVG elements instead of the `graphcool-styles` SVG icon: when not reloading, show the icon, when reloading, show a spinner
Questions
---
> When developing a GraphQL server, you're changing your schema quite often. This workflow is being steadily improved by allowing CMD + R to reload the schema (#180) and even automatic schema reloads based on filewatching via graphqlconfig (#331).
Where are schema changes broadcasted? I'd love to listen to it and thus providing feedback but I couldn't find the code 🙈

Give visual feedback when reloading the schema

---

packages/graphql-playground-react/src/components/Playground/DocExplorer/GraphDocs.tsx
packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx

Fixes #495.
Links shown at the bottom of the autocomplete dropdown were crashing the app everytime.
It should now be fixed, opening the schema explorer everytime we click the links.
The `navStack` is reseted, showing only one tab with the documentation of the type only.
I removed all references to `docExplorerOpen` as it was dead code coming from the original GraphiQL component.
Some tests would be very welcome !

Fixed link to documentation type broken

---

packages/graphql-playground-react/src/components/Playground/SchemaFetcher.ts

This implementation currently fails to send cookies along with a request (even though that was intended).
This is because `credentials: include` is included in the list of headers rather than being passed as an option.
Fixes #505
- Move `credentials: include` from improperly being sent in headers to being passed as an option when fetching schema.

Correctly use cookies when fetching schema

---

packages/graphql-playground-react/src/components/Playground/ExecuteButtonOperation.tsx
packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx
packages/graphql-playground-react/src/components/Playground/Results.tsx
packages/graphql-playground-react/src/components/Spinner.tsx
packages/graphql-playground-react/src/components/Toggle.tsx

I got a bit sidetracked with refactoring apollo-link. I was having a hard time groking 1000 line stateful components so I started doing some cleanup work wherever I saw low hanging fruit. 
I'm working my way into the editor codebase a bit to make it a bit easier to swap out the fetcher.
Here are the granular commits that I have working so far.

Minor cleanup work

---

packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx
packages/graphql-playground-react/src/styles/graphiql_dark.css
packages/graphql-playground-react/src/styles/graphiql_light.css

Fixes #88.
Adding link to docs, currently opens in 2nd column for everything idk how we want to show it.

Adding docs link

---

packages/graphql-playground-react/src/components/Playground/DocExplorer/GraphDocs.tsx

Fix focus and key up + down on first toggle

---

packages/graphql-playground-react/src/components/Playground.tsx
packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx
packages/graphql-playground-react/src/components/Playground/TopBar/TopBar.tsx

- I would like to use graphql-playground on a project that has strict security requirements, and the share button's external request violates our rules. This pr exposes a prop called `shareEnabled` that will allow you to disable the share button.

Add ability to disable share button

---

packages/graphql-playground-electron/src/main/menu.ts

We don't have `Cmd` available on windows :wink:
Fixes #513 .
- Use `CmdOrCtrl` instead of `Cmd` to support windows shortcuts syntax
Note: I can't test on my computer due to some issue with the webpack configuration…
Ref: https://github.com/electron/electron/blob/master/docs/tutorial/keyboard-shortcuts.md

Fix windows keyboard shortcuts

---

README.md

I think a lot of users just click on that picture, but the picture itself opens. Now it will open the link, which might be a bit easier.

Docs: graphqlbin image refers to link

---

packages/graphql-playground-middleware-koa/package.json

also be less strict on the peer dependency version and accept any koa version 2

koa middleware: move koa from dependencies to devDependencies

---

README.md

The example in the README for using the library as a React component appears to be incorrect or out-of-date and results in this error:
> Could not find "store" in either the context or props of "Connect(PlaygroundWrapper)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(PlaygroundWrapper)".
This PR fixes the problem and is modeled on the way the store is passed in the [Electron package](https://github.com/prismagraphql/graphql-playground/blob/master/packages/graphql-playground-electron/src/renderer/components/Root.tsx).

Fix docs for usage as a React component.

---

packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx

- missing prop was preventing rendering of tracing results
- Message "Please re-run the query to show tracing results." was shown even though results were available

Fix broken tracing UI

---

packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts

This PR removes an unnecessary `console.log` call in `fetchingSagas.ts`

Nuke console.log from fetchingSagas.ts

---

packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts

Fixes #652.
`apollo-link-http` will return a "result" object (if it can) inside its error object. This result object will have details from the GraphQL server about the error.
This PR adds simple logic to `extractMessage` to return that result JSON up to the UI.
It may be prudent in the future to add logic to extract data from the myriad of different Apollo Link errors (https://github.com/apollographql/apollo-link/blob/a79f47e8ae81ee2444d547315be61dbafea37dcb/packages/apollo-link-http-common/src/index.ts#L14-L29), but for now this should suffice.

Output 'result' from apollo-link-http error

---

README.md
packages/graphql-playground-react/src/components/PlaygroundWrapper.tsx
packages/graphql-playground-react/src/state/workspace/reducers.ts

Fixes #758.
- Refactor mapStateToProps of PlaygroundWrapper connect to allow custom settings & theme props
- Update getTheme of workspace reducers to use custom settings for theme selection if provided

Fix custom theme and settings

---

packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts
packages/graphql-playground-react/src/state/sessions/sagas.ts
packages/graphql-playground-react/src/utils.ts

Fix prettier incorrect query

---

packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts

Fixes #804.
- GraphQL Extensions are not always hidden from the results view.
- When the `tracing.hideTracingResponse` setting is enabled, tracing is hidden from the results view as advertised in the docs.

Show graphql extensions

---

packages/graphql-playground-react/src/components/Playground/DocExplorer/FieldDoc.tsx

A little change about the color of a comment from a query or mutation.
Before: 
After:
It's take the same style `.black50` as inside the comment for a scalar for example.

Update color in query/mutation comment

---

packages/graphql-playground-electron/package.json
packages/graphql-playground-middleware-express/package.json
packages/graphql-playground-middleware-hapi/package-lock.json
packages/graphql-playground-middleware-hapi/package.json
packages/graphql-playground-middleware-koa/package.json
packages/graphql-playground-middleware-lambda/package.json
packages/graphql-playground-react/package.json
scripts/release-html.sh
scripts/release-react.sh

run ./scripts/release-react.sh, robust jq test and bump electron

---

packages/graphql-playground-react/package.json
packages/graphql-playground-react/src/components/Playground/Tab.tsx
packages/graphql-playground-react/src/components/Playground/TabBar.tsx
packages/graphql-playground-react/src/state/sessions/actions.ts
packages/graphql-playground-react/src/state/sessions/reducers.ts
packages/graphql-playground-react/yarn.lock

I keep trying to do this and it doesn't work, so I thought I would implement it 🙂
Two questions about the implementation details:
- In chrome the new tab button disappears when you are dragging tabs, so that's how I implemented it here.  However the playground tab is a little more visible, so I was thinking about maybe leaving it visible and making it the right border of the draggable area.  Anyone have thoughts on what looks best?
- In chrome dragging a tab also makes it the active tab.  I was having trouble getting the dragged tab to look "active".  I think I know how I could do it, but I'm not sure how much people expect this behavior, so I thought I would ask first if it should be implemented.
Also, the snapshot tests are failing.  Should I go ahead and update them in the PR?

Make tabs sortable

---

packages/graphql-playground-react/src/components/Playground/Tab.tsx

A new session's name will initially be `undefined`, so I ensured that the value we pass to the input will always be a string.  This fixes the React warning `Warning: A component is changing an uncontrolled input of type undefined to be controlled` that was appearing when you rename a tab.

Fix warning about uncontrolled input

---

packages/graphql-playground-react/public/index.html
packages/graphql-playground-react/src/__snapshots__/index.test.tsx.snap
packages/graphql-playground-react/src/components/GraphQLBinApp.tsx
packages/graphql-playground-react/src/components/PlaygroundWrapper.tsx
packages/graphql-playground-react/src/index.test.tsx

Feature implementation for #636 .
- Add `headers` option to `GraphQLPlayground.init()`
- Add `headers` property to `GraphQLBinApp` and pass it through to `PlaygroundWrapper`
- Combine endpoint headers and default headers when passing through to `Playground`

Adding default header option to GraphQLPlayground.init()

---

packages/graphql-playground-html/src/render-playground-page.ts

Allow the cdn url to be passed in to renderPlaygroundPage as an option. This is to support graphql-playground being used offline by tools such as Apollo Server. See https://github.com/apollographql/apollo-server/issues/1421

renderPlaygroundPage - cdnUrl config option

---

packages/graphql-playground-react/src/components/Playground/util/getQueryTypes.ts

- This change allows to use queries/mutations [operation name](https://graphql.org/learn/queries/#operation-name) as `firstOperationName` value.

Use query definition name as firstOperationName if any

---

packages/graphql-playground-html/package.json
packages/graphql-playground-html/yarn.lock
packages/graphql-playground-middleware-express/package.json
packages/graphql-playground-middleware-express/yarn.lock
packages/graphql-playground-middleware-lambda/package.json
packages/graphql-playground-middleware-lambda/yarn.lock

- Bumps `graphql-config` to latest version to enable its dep in `graphql-yoga` to support graphql 14.

fix(graphql 14): version bump via graphql-config

---

packages/graphql-playground-middleware-express/README.md
packages/graphql-playground-middleware-koa/README.md
packages/graphql-playground-react/README.md

Fixes #719.
* Add a basic README for `graphql-playground-middleware-express`
* Add a basic README for `graphql-playground-middleware-koa`
* Update renamed/broken links in `graphql-playground-react` README

README updates

---

packages/graphql-playground-react/src/components/Playground/EditorWrapper.tsx

Fixes #832.
As noted in the issue the lint tooltip text has not been visible in Firefox. This is due to the use of `color: infotext` with `background-color: white`. `color: infotext` is a browser dependent color that is black in Chrome but white in Firefox. [Per MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#System_Colors) `color: infotext` should be paired with `background-color: infobackground` as I have done in this pull request. 
Note that this changes the tooltip style in Chrome as well.
- Change the lint tooltip background-color to infobackground
**In Firefox**:
Before:
After:
**In Chrome:**
Before:
After:

Fix lint tooltip background to be infobackground (#832)

---

packages/graphql-playground-html/package.json
packages/graphql-playground-html/src/render-playground-page.ts
packages/graphql-playground-html/yarn.lock

Remove config dependency to reduce size of `html` package

Remove graphql-confing

---

packages/graphql-playground-react/src/components/Playground/SchemaFetcher.ts

Fixes https://github.com/prisma/graphql-playground/issues/864.
- Address empty array errors as no errors

fix: do not throw error when server response with empty array errors

---

packages/graphql-playground-react/src/components/Playground/DocExplorer/ColumnDoc.tsx

Some issue with styled-components is causing warning message
Fixes #894 
- Changing property name

Changed property name to remove warning

---

packages/graphql-playground-react/src/components/Playground/DocExplorer/TypeLink.tsx

Fixes #903.
We now run JSON.stringify on type.default so that it is always a string and can be displayed.
There is no chance there will a circular object in the default values so this should fix the current problem

Support non primitive types for default value

---

packages/graphql-playground-react/src/components/Playground/ExplorerTabs/SideTabs.tsx
packages/graphql-playground-react/src/components/Playground/SchemaExplorer/SDLEditor.tsx

Fixes #907.
Actually, the code to power the closing via keyboard handler was already in place. But the focus state of the sidebar was not managed properly so the sidebar was not closing.
This PR address the focus management

Close sidebar on pressing escape

---

packages/graphql-playground-react/src/state/sessions/reducers.ts

An empty headers dict currently is not treated as having 'no headers to inject'
Discussed in: https://github.com/prisma/graphql-playground/issues/893
Fixes #893 (at least in the case where headers are empty).
-  Fix logic in checking if headers are empty in INJECT_HEADERS

Update headers are empty check on INJECT_HEADERS

---

README.md
packages/graphql-playground-react/src/components/Playground.tsx
packages/graphql-playground-react/src/components/PlaygroundWrapper.tsx
packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts

Fixes #919
- Make sure the subscription endpoint is sent as a parameter to link creator to make it more straight forward to build a custom link creator
Let me know if you think this is reasonable, and I'll update the type specifications and documentation to reflect this as well.

send the subscription endpoint as parameter to link creator

---

README.md
packages/graphql-playground-react/src/components/Playground/QueryEditor.tsx
packages/graphql-playground-react/src/components/Playground/util/createSDL.ts
packages/graphql-playground-react/src/state/sessions/sagas.ts
packages/graphql-playground-react/src/state/sessions/selectors.ts
packages/graphql-playground-react/src/state/workspace/reducers.ts
packages/graphql-playground-react/src/types.ts
packages/graphql-playground-react/src/utils.ts
scripts/build.sh

- Ability to use prettier options `useTabs` and `tabWidth`
We keep copies of test queries and mutations in our code for documentation and our prettier settings are different than the prettier settings in playground.  This means when we copy back and forth, we have issues with whitespace.
This should fix those issues.

Additional Prettier Options

---

packages/graphql-playground-html/src/render-playground-page.ts

This PR adds the `editor.cursorShape` key to the `ISettings` interface.

add editor.cursorShape to ISettings interface

---

package.json
packages/graphql-playground-react/package.json
packages/graphql-playground-react/src/components/Playground.tsx
packages/graphql-playground-react/src/components/Playground/SchemaFetcher.ts
packages/graphql-playground-react/src/components/Playground/TopBar/Polling.tsx
packages/graphql-playground-react/src/components/Playground/TopBar/SchemaReload.tsx
packages/graphql-playground-react/src/components/Playground/TopBar/TopBar.tsx
packages/graphql-playground-react/src/components/PlaygroundWrapper.tsx
packages/graphql-playground-react/src/components/util.ts
packages/graphql-playground-react/src/state/sessions/reducers.ts
packages/graphql-playground-react/src/state/sessions/sagas.ts
packages/graphql-playground-react/src/state/workspace/deserialize.ts
packages/graphql-playground-react/yarn.lock
yarn.lock

Make schema reloading more resilient. Closes #940

---

packages/graphql-playground-html/src/render-playground-page.ts

Fixes #921.
Fixes #216.
- Remove the hardcoded favicon `graphcool-playground.netlify.com` path.
This hardcoded path never actually did anything as it was replaced by a further `shortcut icon` link after, so is being removed for hygiene.
Before:
```
<link rel="shortcut icon" href="https://graphcool-playground.netlify.com/favicon.png">
<title>GraphQL Playground</title>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/graphql-playground-react@1.7.8/build/static/css/index.css" />
<link rel="shortcut icon" href="//cdn.jsdelivr.net/npm/graphql-playground-react@1.7.8/build/favicon.png" />
```
After:
```
<title>GraphQL Playground</title>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/graphql-playground-react@1.7.8/build/static/css/index.css" />
<link …
```

Remove hardcoded favicon.

---

packages/graphql-playground-react/src/components/ProjectsSideNav.tsx
packages/graphql-playground-react/src/components/ProjectsSideNavItem.tsx

I've done some restyling of ProjectsSideNav and ProjectsSideNavItem, simplified CSS, made them a bit more responsive using flexbox and removed some not needed tags. Hit me up if you have any suggestions.
Let me know if you like it and I'll be more than happy to work on something similar for some other parts of the app.
Some edge case examples
Before
After

Restyle ProjectsSideNav

---

packages/graphql-playground-html/package.json
packages/graphql-playground-middleware-express/package.json
packages/graphql-playground-middleware-hapi/package.json
packages/graphql-playground-middleware-koa/package.json
packages/graphql-playground-middleware-lambda/package.json
packages/graphql-playground-react/package.json

Reverting license fields back to MIT to restore automated license-testing consumers
Fixes #959 .
- Restored the license fields in each package.json to be the proper SPDX identifier: `"MIT"`

Restored package.json license fields to MIT

---

packages/graphql-playground-middleware-express/src/index.ts

Fixes #557.
Fixes #752.
- Avoid calling `next()` in express middleware after `res.end()`. This causes other middleware to be called afterward, and since this is a rendering middleware, it will throw
`[ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

Avoid calling next() in Express middleware

---

packages/graphql-playground-electron/src/main/menu.ts

Fixes #964
- New menu option to hide the application + separator, both visible only on mac
Couldn't find any info regarding the `Hide Others` electron api tho, please let me know if I've missed it and its implemented.

Add hide menu option on mac

---

README.md
packages/graphql-playground-html/minimalWithoutCDN.html

Fixes #.
- Add an example for usage of the markup renderer without a CDN like (jsDelivr)

Add an example for usage of graphql-playground-html without jsDelivr

---

packages/graphql-playground-react/src/components/Playground/ResultViewer.tsx

Fixes #.
Problem: When working with subscriptions, each subscription item had a little scrollbar attached to each item. This would make scrolling janky. This pull request removes this double scrollbar.

Remove internal scrollbars for subscription results

---

packages/graphql-playground-react/src/components/Playground/ExecuteButton.tsx

- prevent selection of text when one did mousedown on the execute button or the execute box and then did mouseup outside of them.
the version not fixed

fix(graphql-playground-react): prevent selection of text

---

packages/graphql-playground-react/src/components/Playground/Tab.tsx
packages/graphql-playground-react/src/components/Playground/TabBar.tsx
packages/graphql-playground-react/src/components/ProjectsSideNav.tsx

Fixes #973 .
Apparently reordering tabs is already implemented, but got overwritten by the dragging area of the tab bar and it's wasn't possible to grab them. Furthermore, I've added the no-drag to config icon and plus icon as it seemed to be more intuitive.

Adjust dragging area

---

packages/graphql-playground-react/src/components/Playground/ExplorerTabs/SideTabs.tsx

- This PR for resolving the following console warning, which appears when a side tab isn't active.
```
Warning: Received `false` for a non-boolean attribute `color`.
If you want to write it to the DOM, pass a string instead: color="false" or color={value.toString()}.
If you used to conditionally omit it with color={condition && value}, pass color={condition ? value : undefined} instead.
```

fix: 'false' into a non-boolean attribute 'color'

---

packages/graphql-playground-react/src/components/Playground/util/createSDL.ts

- fix the filename given to the schema when downloaded using the JSON download button in the schema viewer

fix typo in downloaded schema filename

---

packages/graphql-playground-html/src/render-playground-page.ts

Fixes:  #1041.
- adds `name?: string` to `Tab` itnerface

Adds `name` property to `Tab` interface.

---

.dependabot/config.yml

because yarn workspaces was disabled at some point, dependabot is only monitoring the root yarn.lock. danger!
if you enable workspaces and update the underlying versions, and do yarn audit, you'll see more than dependabot reports (which is just the root it seems?)
github shows all the vulnerabilities in all lockfiles very prominently, however
this also adds conventional commits support so we don't have to rename the PRs for them to pass the CI in place

chore: introduce dependabot config

---

packages/graphql-playground-middleware-express/package.json

graphql-playground-middleware-express package.json should now point to the latest version of html.
My team's licensing automation is still failing because the 1.6.13 fixes aren't being picked up by this pinned version

fix(deps): Update express mw to latest graphql-playground-html

---

packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx

Currently is not possible to see all the events of a subscription in the results pane for lack of a css property, this pull request fix #1021 this.

fix: Allow scroll in result panel

---

packages/graphql-playground-react/src/components/Playground/ResultViewer.tsx

Currently, the results pane is limited to a maximum width of `50vw`. When the pane is resized (to view long stack trace lines for example), the pane contents don't expand to fill the new space.
This PR fixes that by allowing the results pane to expand to fill the available horizontal space.
- Remove the `max-width` CSS rule for `.CodeMirror-scroll`.
|Before|After|
|-|-|
|<img width="1303" alt="Screen Shot showing long lines being wrapped even though there's ample space on the right side to display them unwrapped." src="https://user-images.githubusercontent.com/5957867/77918505-fd002880-7269-11ea-8b9b-c1a356008c4e.png">|<img width="1303" alt="Screen Shot showing long lines wrapped to fill the available horizontal space." …

fix: allow results to fill the entire pane horizontally

---

packages/graphql-playground-react/src/components/SettingsEditor.tsx

Fixes #1197.
[I broke this](https://github.com/prisma-labs/graphql-playground/pull/1191/files#diff-42484cc8d8c06e5994466038a84cd221R109) while updating TypeScript a few days back. 
There might be a better fix but for now this gets the job done.

fix: workaround for bug in SettingsEditor

---

packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx

Fixes #1140 
- `runQueryAtCursor` shouldn't check if the query editor is on focus, as it will never be when used by Variable and Header editor

feat: run query on variable, header editor through ctrl+enter

---

README.md
packages/graphql-playground-html/src/render-playground-page.ts
packages/graphql-playground-react/src/components/Playground.tsx
packages/graphql-playground-react/src/components/Playground/SchemaFetcher.ts
packages/graphql-playground-react/src/state/workspace/reducers.ts
packages/graphql-playground-react/src/types.ts

Fixes #490.
- Add  `tracing.tracingSupported` setting that when false removes `x-apollo-tracing` header from schemaFetch requests
- Don't send `x-apollo-tracing` header if `initialSchemaFetch ` is `true`

fix: X-Apollo-Tracing No Schema Issue

---

packages/graphql-playground-react/src/components/Playground.tsx

refs #1112.
- use `props.settings['tracing.tracingSupported']` instead of `this.props.settings['tracing.tracingSupported']` same as `request.credentials`
- use `propsInput` as first instead of `this.props`. `this.props` is always non-null. maybe the opposite of the intention. `settings` doesn't exists in `this.props` at first.
@acao please take a look. I look forward to the release of #1112 🌹

fix: schemaGetter props handling

---

packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx

Fixes # N/A.
It took a while to track down but there is a closing curly bracket that's unnecessary. It gets rendered in output and it's visible on white background. I removed it. This was introduced in #1001 https://github.com/prisma-labs/graphql-playground/pull/1001/files#diff-977e6e5ed829c1b17ed396af79ae26b3R291
This is a screenshot from master
This is a screenshot from the Netlify preview app

Removed unnecessary } in GraphQLEditor

---

packages/graphql-playground-react/README.md

It still refers to the old package

graphql-playground -> graphql-playground-react

---

lerna.json

because users expect an electron build for this, which we can't produce yet.

fix: don't gh release on lerna publish

---

packages/graphql-playground-html/examples/xss-attack/README.md
packages/graphql-playground-html/examples/xss-attack/index.js
packages/graphql-playground-html/examples/xss-attack/package.json

- fix: missing apollo-server-express which is necessary
- fix: wrong endpoint
- docs: add URI for example 4 (@acao I think that is what you intended to do but you've forgot to do that, is that right? :))

fix(examples): fix examples of reflected XSS attack

---

packages/graphql-playground-react/src/components/Playground/util/createSDL.ts

I have been using Playground for a while now with a GraphQL API developed in ASP.NET Core, using the open source library graphql-dotnet.
Everytime I download the SDL schema from Playground, there are several comment lines with line breaks in the middle, which makes the exported file invalid until I manually delete all unwanted line breaks.
After investigation, I found out that the library graphql-dotnet brings comments for scalar types containing the word "scalar" (like [this one](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Scalars/DateGraphType.cs)) or even with closing braces in it (for example the [connection type](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Relay/ConnectionType.cs)).
So, those comment lines are …

fix: 'addLineBreaks' regex in 'createSDL' to avoid line-breaking comment lines

---

packages/graphql-playground-html/examples/xss-attack/.envrc

It seems that .envrc has been used at some point during local development before pushing to merge (#1231), but seems that it  isn't being used any more since PORT is being declared in index.js.

refactor: remove unnecessary envrc file

---

packages/graphql-playground-middleware-koa/src/index.ts

Added the KoaPlaygroundMiddlewareOptions alias so that packages that want to pass around or preset the options don't have to fight the `eslint(import/no-extraneous-dependencies)` warning.
Fixed the signature of KoaPlaygroundMiddleware to actually match the usage: Koa expects this signature and the previous way was making things mighty hard to use, plus any function that is async is supposed to return a Promise anyway.
I think the tslint hint could be dropped now, but I'm creating this commit from GitHub's interface no I'm not sure. Also I think both KoaPlaygroundMiddleware and Register types could be dropped and the type declarations inlined on the actual lambdas, but I don't know if the extant pattern had a good reason or was just C&P from something else.

fix: Koa middleware interface

---

packages/graphql-playground-react/src/components/Playground/TopBar/TopBar.tsx

Fixes #1219.
This fixes the error `TypeError: t.context.store is undefined ` which currently occurs whenever you click on "Copy CURL".

Fix error with Copy CURL

---

README.md

- Documentation update because of brew changes:
> Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.

Update install instruction in README.md

---

packages/graphql-playground-react/src/__snapshots__/index.test.tsx.snap
packages/graphql-playground-react/src/components/Playground/GraphQLEditor.tsx

- Updates empty state to use less violent verb 'play' rather than 'hit' (we have a client who commented on this and there doesn't seem to be any way to modify this phrase without forking).
- Updates jest snapshots to match
Please let me know if you have any concerns. Thanks!

[graphql-playground-react] Change 'Hit the Play Button' to 'Press the Play Button'

---

.github/CONTRIBUTING.md

Fixes contributor code of conduct link in [CONTRIBUTING.md](https://github.com/graphql/graphql-playground/blob/2be0d9bc8070f5c9841c06d807c292f6828610f9/.github/CONTRIBUTING.md).
- Current [Contributor Code of Conduct link](https://github.com/graphql/graphql-playground/blob/2be0d9bc8070f5c9841c06d807c292f6828610f9/.github/CONTRIBUTING.md) is broken and redirects to a 404.

docs: fix contributor code of conduct link

---

packages/graphql-playground-html/src/render-playground-page.ts

We should be able to only set the settings that we want to set without having to give a value for every parameters.
This PR fixes that.

fix: make Playground's middleware settings optional

---

README.md

Update install command to solve the issue
> Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
This is new command based on https://brew.sh/
BTW, nice tool!

docs(readme): update install command

---

packages/graphql-playground-react/src/components/Playground/EditorWrapper.tsx

This change adjusts the CSS stylings for the colours of the CodeMirror "search" dialog, which appears temporarily when pressing Ctrl-F/Cmd-F within the query or response frames of GraphQL Playground, to be visible within the light theme.  It slightly improves the visibility on the dark theme as well!
> Note, there is text there, it's just impossible to see!
Fixes: https://github.com/apollographql/apollo-server/issues/2117

Adjust colours of CodeMirror "Find" dialog on "light" background.

---

README.md

-  Remove an outdated hiatus notice from README.md.

Added 'Seeking Maintainers' notice
