packages/graphql-playground/src/components/Playground/DocExplorer/GraphDocs.tsx

Fix space in docs

---

packages/graphql-playground-electron/src/InitialView/InitialView.tsx

Looking forward to playing with the playground! 🎉

fix(desktop): allow urls without tld - fixes #138

---

packages/graphql-playground-electron/README.md
packages/graphql-playground-electron/package.json

Hi!
A very small fix: windows don't deal with simple quote into command line 😉

Fix start command on windows

---

packages/graphql-playground-electron/src/main.ts

[WIP] Adds auto-updating using Hazel

---

packages/graphql-playground/src/components/Playground.tsx

We might want to make it configurable via the options, please let me know if this is something that we want
Closes #159

include cookies to the graphql query requests

---

packages/graphql-playground/src/components/EndpointPopup.tsx

Fix https in endpoint

---

.github/PULL_REQUEST_TEMPLATE.md

Adds a pull request template with specific placeholders for issue number and change descriptions

Adds PULL_REQUEST_TEMPLATE

---

packages/graphql-playground/src/components/Playground.tsx
packages/graphql-playground/src/components/Playground/onHasCompletion.tsx
packages/graphql-playground/src/components/SettingsEditor.tsx
packages/graphql-playground/typings/custom.d.ts

Version added to global window object + in setting tab. Version is already in electron app in about.

Adding version to playground 🚀

---

.circleci/config.yml
.vscode/settings.json
packages/graphql-playground-react/src/components/Playground.tsx

Fix reload + circleci

---

README.md

Readme rename of package

---

packages/graphql-playground-react/src/components/ProjectsSideNav.tsx

Draggable header fix #329 🚀

---

packages/graphql-playground-react/src/components/HistoryPopup.tsx

Fix history scroll #313

---

packages/graphql-playground-react/src/styles/graphiql_dark.css
packages/graphql-playground-react/src/styles/graphiql_light.css

Fix tooltip message wrapping

---

README.md

Fixes "Circle CI" and "Build status" badges, updates the OSS love image

Fix CircleCI and build status badges, update "we ❤️ OSS"

---

.circleci/config.yml

- configure / set the CircleCI cache

chore: set CircleCI cache

---

README.md

Fixes announcement link of README.
- Add a closing bracket 😄

Fix announcement link

---

packages/graphql-playground-react/package.json
packages/graphql-playground-react/yarn.lock

Introducing [bundlesize ](https://github.com/siddharthkp/bundlesize)

Bundlesize

---

packages/graphql-playground-react/src/state/sessions/reducers.ts
packages/graphql-playground-react/src/state/sessions/sagas.ts
packages/graphql-playground-react/src/state/workspace/reducers.ts
packages/graphql-playground-react/src/types.ts
packages/graphql-playground-react/src/utils.ts

Prettier settings in config

---

packages/graphql-playground-react/src/components/Playground/ConfigEditor.tsx

Fix line number in settings tab

Fix settings

---

packages/graphql-playground-react/src/constants.ts

Changed `Try to write your query here` to `Write your query or mutation here` 😀

Changed comment on input page.

---

packages/graphql-playground-html/withAnimation.html

There's a missing body closing tag in some html. I added it.

fix: close body tag

---

README.md

Wasted a lot of time assuming this was properly implemented.

Clarify graphql-config support.

---

packages/graphql-playground-react/src/components/Playground/DocExplorer/RootColumn.tsx

Fix overflow docs

---

packages/graphql-playground-react/src/components/ProjectsSideNav.tsx

Fixes #929
- new workspace button should now be visible only in electron

Make new workspace button visible only in electron

---

packages/graphql-playground-electron/package.json
packages/graphql-playground-electron/yarn.lock
packages/graphql-playground-react/package.json
packages/graphql-playground-react/yarn.lock

https://www.npmjs.com/advisories/826

Upgrade webpack-bundle-analyzer to 3.3.2

---

README.md

- Fix the broken CircleCI badge.
- Add a direct link to #1143 to let visitors know its current status.

docs: Fix CircleCI badge, add link to the GraphiQL issue in README

---

packages/graphql-playground-react/README.md

Fix typo/spelling mistake
Fixes 1.
- Fix typo/spelling mistake

fix: Update README.md

---

SECURITY.md
packages/graphql-playground-html/README.md
packages/graphql-playground-html/package.json
packages/graphql-playground-middleware-express/README.md
packages/graphql-playground-middleware-hapi/README.md
packages/graphql-playground-middleware-koa/README.md
packages/graphql-playground-middleware-koa/package.json
packages/graphql-playground-middleware-lambda/README.md
packages/graphql-playground-middleware-lambda/package.json

gets all the versions right (lerna publish funny business again)

fix: rectify all versions and references

---

yarn.lock

fix: necessary lockfile changes

---

lerna.json

chore: add lerna publish

---

.github/workflows/publish.yml

attempt to publish on merge
Fixes #.
- 
- 
-

ci: publish on merge

---

README.md
SECURITY.md
packages/graphql-playground-html/examples/xss-attack/.envrc
packages/graphql-playground-html/examples/xss-attack/README.md
packages/graphql-playground-html/examples/xss-attack/index.js
packages/graphql-playground-html/examples/xss-attack/package.json
packages/graphql-playground-middleware-express/package.json

Shows some examples of the reported XSS Reflection attack

chore: example xss attack

---

README.md

docs: improve security docs in Readme

---

packages/graphql-playground-html/examples/xss-attack/README.md

docs: more info about xss vulnerability

---

packages/graphql-playground-html/src/render-playground-page.ts

Removes `/` character in url that shouldn't be there.

fix: cdn url

---

packages/graphql-playground-html/src/render-playground-page.ts

Fixes #1211.
* add schema.polling settings to TS ISettings interface.

fix: add schema.polling* to ISettings interface.

---

README.md
packages/graphql-playground-react/README.md

Fixes #1271 
- Update from old Slack link to Discord link

Add Discord invite
